name: Deploy

on:
    push:
        branches: ['main']

    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Build project
              run: npm run build

            - name: Format project
              run: npm run prettier

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v2
              with:
                  name: production-files
                  path: ./dist
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  name: production-files
                  publish_dir: ./dist
                  cname: cofymdd.com
                  publish_branch: website
